/**
 * CropVision SaaS - Digital Field Book Store (Caderno de Campo Oficial)
 * Complies strictly with Portuguese DGAV & European CAP (PAC 2023-2027) regulatory requirements:
 * - Decree-Law 145/2015 & Portaria 229/2013 (Phytosanitary application tracking)
 * - EU Nitrates Directive 91/676/EEC & GAEC 4/8 cross-compliance records.
 */

export interface PhytosanitaryRecord {
  id: string;
  date: string; // YYYY-MM-DD
  farmId: string;
  parcelName: string;
  crop: string;
  commercialProduct: string;
  homologationNumber: string; // Nº APV ou autorização de venda
  activeSubstance: string;
  dose: number;
  unit: 'l/ha' | 'kg/ha';
  sprayVolumeLHa: number; // Volume de calda em l/ha
  targetOrganism: string; // Inimigo / Justificação técnica
  safetyIntervalDays: number; // Intervalo de segurança (dias)
  applicatorName: string;
  applicatorCardNumber: string; // Nº Cartão de Aplicador homologado
  operatorNotes?: string;
}

export interface FertilizationRecord {
  id: string;
  date: string; // YYYY-MM-DD
  farmId: string;
  parcelName: string;
  crop: string;
  fertilizerType: 'mineral' | 'organico' | 'fertirrega' | 'foliar';
  commercialProduct: string;
  rateKgHa: number; // Quantidade comercial kg/ha ou l/ha
  nutrientUnitsN: number; // Unidades de Azoto N kg/ha
  nutrientUnitsP2O5: number; // P2O5 kg/ha
  nutrientUnitsK2O: number; // K2O kg/ha
  vraPrescriptionLinked: boolean; // Flagged if generated by CropVision VRA engine
  technicalNotes?: string;
}

const PHYTO_STORAGE_KEY = 'cropvision_fieldbook_phyto_v1';
const FERT_STORAGE_KEY = 'cropvision_fieldbook_fert_v1';

const DEFAULT_PHYTO_RECORDS: PhytosanitaryRecord[] = [
  {
    id: 'phyto-1',
    date: '2026-05-12',
    farmId: 'farm-esporao',
    parcelName: 'Talhão 1 - Vinha do Almotrém',
    crop: 'Vinha (Aragonez)',
    commercialProduct: 'Cuprocol',
    homologationNumber: 'APV nº 3624',
    activeSubstance: 'Oxicloreto de Cobre (50% Cu)',
    dose: 2.5,
    unit: 'kg/ha',
    sprayVolumeLHa: 400,
    targetOrganism: 'Míldio da Vinha (Plasmopara viticola)',
    safetyIntervalDays: 14,
    applicatorName: 'João Carlos Ferreira',
    applicatorCardNumber: 'APL-EVR-89412',
    operatorNotes: 'Tratamento preventivo após precipitação de 18mm (Regra dos Três Dez).',
  },
  {
    id: 'phyto-2',
    date: '2026-06-04',
    farmId: 'farm-esporao',
    parcelName: 'Talhão 1 - Vinha do Almotrém',
    crop: 'Vinha (Aragonez)',
    commercialProduct: 'Flint Max',
    homologationNumber: 'APV nº 0411',
    activeSubstance: 'Trifloxistrobina (25%) + Tebuconazol (50%)',
    dose: 0.3,
    unit: 'kg/ha',
    sprayVolumeLHa: 450,
    targetOrganism: 'Oídio da Vinha (Erysiphe necator)',
    safetyIntervalDays: 21,
    applicatorName: 'João Carlos Ferreira',
    applicatorCardNumber: 'APL-EVR-89412',
    operatorNotes: 'Aplicação no fecho dos cachos com tempo calmo (vento < 8 km/h).',
  },
];

const DEFAULT_FERT_RECORDS: FertilizationRecord[] = [
  {
    id: 'fert-1',
    date: '2026-03-20',
    farmId: 'farm-esporao',
    parcelName: 'Talhão 1 - Vinha do Almotrém',
    crop: 'Vinha (Aragonez)',
    fertilizerType: 'mineral',
    commercialProduct: 'Nitrato de Amónio Calcário CAN-27',
    rateKgHa: 145,
    nutrientUnitsN: 39.2,
    nutrientUnitsP2O5: 0,
    nutrientUnitsK2O: 0,
    vraPrescriptionLinked: true,
    technicalNotes: 'Prescrição VRA CropVision gerada por satélite Sentinel-2 para compensação de clorose.',
  },
  {
    id: 'fert-2',
    date: '2026-04-28',
    farmId: 'farm-esporao',
    parcelName: 'Talhão 1 - Vinha do Almotrém',
    crop: 'Vinha (Aragonez)',
    fertilizerType: 'fertirrega',
    commercialProduct: 'Nitrato de Potássio 13-0-46',
    rateKgHa: 60,
    nutrientUnitsN: 7.8,
    nutrientUnitsP2O5: 0,
    nutrientUnitsK2O: 27.6,
    vraPrescriptionLinked: false,
    technicalNotes: 'Injeção por gota-a-gota no período de floração e vingamento.',
  },
];

export function loadPhytosanitaryRecords(): PhytosanitaryRecord[] {
  if (typeof window === 'undefined') return DEFAULT_PHYTO_RECORDS;
  try {
    const raw = localStorage.getItem(PHYTO_STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(PHYTO_STORAGE_KEY, JSON.stringify(DEFAULT_PHYTO_RECORDS));
      return DEFAULT_PHYTO_RECORDS;
    }
    return JSON.parse(raw);
  } catch {
    return DEFAULT_PHYTO_RECORDS;
  }
}

export function savePhytosanitaryRecord(record: Omit<PhytosanitaryRecord, 'id'>): PhytosanitaryRecord {
  const current = loadPhytosanitaryRecords();
  const created: PhytosanitaryRecord = {
    ...record,
    id: `phyto-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
  };
  const updated = [created, ...current];
  try {
    localStorage.setItem(PHYTO_STORAGE_KEY, JSON.stringify(updated));
  } catch {}
  return created;
}

export function deletePhytosanitaryRecord(id: string): PhytosanitaryRecord[] {
  const current = loadPhytosanitaryRecords();
  const updated = current.filter((r) => r.id !== id);
  try {
    localStorage.setItem(PHYTO_STORAGE_KEY, JSON.stringify(updated));
  } catch {}
  return updated;
}

export function loadFertilizationRecords(): FertilizationRecord[] {
  if (typeof window === 'undefined') return DEFAULT_FERT_RECORDS;
  try {
    const raw = localStorage.getItem(FERT_STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(FERT_STORAGE_KEY, JSON.stringify(DEFAULT_FERT_RECORDS));
      return DEFAULT_FERT_RECORDS;
    }
    return JSON.parse(raw);
  } catch {
    return DEFAULT_FERT_RECORDS;
  }
}

export function saveFertilizationRecord(record: Omit<FertilizationRecord, 'id'>): FertilizationRecord {
  const current = loadFertilizationRecords();
  const created: FertilizationRecord = {
    ...record,
    id: `fert-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
  };
  const updated = [created, ...current];
  try {
    localStorage.setItem(FERT_STORAGE_KEY, JSON.stringify(updated));
  } catch {}
  return created;
}

export function deleteFertilizationRecord(id: string): FertilizationRecord[] {
  const current = loadFertilizationRecords();
  const updated = current.filter((r) => r.id !== id);
  try {
    localStorage.setItem(FERT_STORAGE_KEY, JSON.stringify(updated));
  } catch {}
  return updated;
}
