import { PresetLocation } from './types';

export const PRESET_LOCATIONS: PresetLocation[] = [
  {
    id: 'esporao-alentejo',
    name: 'Esporão Estate',
    region: 'Alentejo',
    country: 'Portugal',
    cropType: 'Vineyard & Olive Grove',
    lat: 38.3842,
    lon: -7.5519,
    zoom: 14,
    description: 'World-renowned agricultural wine and olive estate in Reguengos de Monsaraz.',
  },
  {
    id: 'sorriso-matogrosso',
    name: 'Cerrado Farm',
    region: 'Sorriso, Mato Grosso',
    country: 'Brazil',
    cropType: 'Soybean & Corn Rotation',
    lat: -12.5425,
    lon: -55.7211,
    zoom: 13,
    description: "South America's agribusiness capital with large-scale commercial precision farm plots.",
  },
  {
    id: 'fresno-california',
    name: 'Central Valley',
    region: 'Fresno, California',
    country: 'United States',
    cropType: 'Almond Orchards & Citrus',
    lat: 36.7378,
    lon: -119.7871,
    zoom: 14,
    description: 'One of the world most productive agricultural valleys operating under high-efficiency drip irrigation.',
  },
  {
    id: 'douro-vallado',
    name: 'Quinta do Vallado',
    region: 'Peso da Régua, Douro',
    country: 'Portugal',
    cropType: 'Terraced Steep Vineyards',
    lat: 41.1601,
    lon: -7.7719,
    zoom: 15,
    description: 'UNESCO World Heritage hillside vineyards on ancient steep sloped terraces.',
  },
  {
    id: 'alqueva-water',
    name: 'Alqueva Reservoir',
    region: 'Moura / Portel',
    country: 'Portugal',
    cropType: 'Water Surface & Irrigation Dam',
    lat: 38.1972,
    lon: -7.4981,
    zoom: 13,
    description: "Western Europe's largest artificial reservoir, ideal for calibrating negative NDVI values over water.",
  },
];
